name: publish image to ACR
on:
  push:

  workflow_dispatch:

env:
  REGISTRY_NAME: fintlabsacr
  NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get repo name
        id: get_repo
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{steps.get_repo.outputs.REPO}}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{steps.get_repo.outputs.REPO}}:${{ github.sha }}

      ## Uncomment to trigger a deployment
      - name: Start deployment workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUBACTION_TOKEN}}
          event-type: trigger-to-deploy